This is makeindex, version 2.15 [TeX Live 2009] (kpathsea + Thai support).
Scanning style file ./report.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file report.acn....done (34 entries accepted, 0 rejected).
Sorting entries....done (198 comparisons).
Generating output file report.acr....done (29 lines written, 0 warnings).
Output written in report.acr.
Transcript written in report.alg.
